### ISSUE TITLE
Better explanation?

### ISSUE THREAD

**Issue by e-3-s** [dawidd6/indicator-spotify#1]
Hi there,

Excuse me to make an issue out if this.
But I really don't understand what this does?
Is it for a website? To put in to?

Could you give us or me a better description.
Ofcourse you can close it afterward.

**Comment by dawidd6** [comment]
As the repo description says, it's:
> Ubuntu (unity) panel indicator

It connects with official Spotify desktop app running on the same machine and displays currently played song in Unity panel.
