### ISSUE TITLE
Icon not showing correctly 

### ISSUE THREAD

**Issue by matsest** [dawidd6/indicator-spotify#2]
## Description

Application does not show Spotify icon in the tray:

![screenshot from 2019-01-15 18-14-32](https://user-images.githubusercontent.com/10927304/51197304-09a89300-18e9-11e9-9cc7-ee4dab0bfab4.png)

## Details 

* Ubuntu 18.04.1 LTS x86_64
* Unity 7.5.0
* Application version: 201801141227+b131e9d+git~ubuntu18.04.1 (installed through apt repo as stated in the readme)

**Comment by dawidd6** [comment]
Thanks for letting me know about this issue!
This should be fixed now.

Simply upgrade the package executing:
```
sudo apt update
sudo apt install indicator-spotify
```
...and let me know if it's alright.

**Comment by matsest** [comment]
Thanks for the quick response! It all seems to be working correctly now :)

**Comment by dawidd6** [comment]
Sure. Glad someone is using my software.

**Comment by matsest** [comment]
As Ubuntu has dropped Unity, I guess most people aren't using it anymore. Even on decent hardware, it's much faster and more responsive than GNOME in my opinion. And Spotify is a must have! Thanks again :)

**Comment by dawidd6** [comment]
Yeah, pity. That's why i'm still using 16.04 and probably will till the end of support.

**Comment by matsest** [comment]
FYI: If you do an in-place upgrade to 18.04, you'll still keep the Unity DE and you'll have 10 years support/security patches, until 2028 (as opposed to until 2021 with 16.04).

**Comment by dawidd6** [comment]
I know. But i saw there are some issues with unity session on 18.04, idk.
